apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2x-backend-deployment
  namespace: p2x
  labels:
    app: p2x-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2x-backend
  template:
    metadata:
      labels:
        app: p2x-backend
    spec:
      containers:
      - name: p2x-backend
        image: p2x-backend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5050
          - containerPort: 6060
        envFrom:
          - configMapRef:
              name: p2x-config
          - secretRef:
              name: genie-app-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: p2x-backend-service
  namespace: p2x
spec:
  selector:
    app: p2x-backend
  ports:
    - name: http-5050
      protocol: TCP
      port: 5050
      targetPort: 5050
    - name: http-6060
      protocol: TCP
      port: 6060
      targetPort: 6060
  type: LoadBalancer
