apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2x-front-deployment
  namespace: p2x
  labels:
    app: p2x-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2x-frontend
  template:
    metadata:
      labels:
        app: p2x-frontend
    spec:
      containers:
      - name: p2x-frontend
        image: bilvantip2x/p2x-nextapp-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: DB_HOST
            value: "p2x-postgres-headless"      
        envFrom:
        - configMapRef:
            name: p2x-config
        - secretRef:
            name: p2x-secrets
            
---
apiVersion: v1
kind: Service
metadata:
  name: p2x-front-service
  namespace: p2x
spec:
  selector:
    app: p2x-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP