apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  namespace: p2x
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgres_data    # Local path on node for DB data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-ddl
  namespace: p2x
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgres_ddl     # Local path on node for ddl/backup files
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: p2x
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: postgres-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ddl
  namespace: p2x
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: postgres-ddl
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: p2x-postgres
  namespace: p2x
spec:
  serviceName: p2x-postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: p2x-postgres
  template:
    metadata:
      labels:
        app: p2x-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "p2x"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: p2x-secrets
              key: DB_PASS
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-ddl
          mountPath: /mnt/backup
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
      - name: postgres-ddl
        persistentVolumeClaim:
          claimName: postgres-ddl
---
apiVersion: v1
kind: Service
metadata:
  name: p2x-postgres-headless
  namespace: p2x
spec:
  spec:
    clusterIP: None 
  selector:
    app: p2x-postgres
  ports:
    - port: 5432
      targetPort: 5432
  
