apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: p2x-postgres
  namespace: p2x
spec:
  serviceName: p2x-postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: p2x-postgres
  template:
    metadata:
      labels:
        app: p2x-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "p2x"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: p2x-secrets
              key: DB_PASS
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard

---

apiVersion: v1
kind: Service
metadata:
  name: p2x-postgres-headless
  namespace: p2x
spec:
  clusterIP: None
  selector:
    app: p2x-postgres
  ports:
    - port: 5432
      targetPort: 5432


