apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2x-temporal-app-deployment
  namespace: p2x
  labels:
    app: p2x-temporal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2x-temporal-app
  template:
    metadata:
      labels:
        app: p2x-temporal-app
    spec:
      containers:
      - name: p2x-temporal-app
        image: sivareddy6244/temporal-app:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
        env:
        - name: TEMPORAL_SERVER_URL
          value: "temporal:7233"
        envFrom:
          - configMapRef:
              name: p2x-config
          - secretRef:
              name: p2x-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: p2x-temporal-app-service
  namespace: p2x
spec:
  selector:
    app: p2x-temporal-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
