apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2x-temporal-ui-deployment
  namespace: p2x
  labels:
    app: p2x-temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2x-temporal-ui
  template:
    metadata:
      labels:
        app: p2x-temporal-ui
    spec:
      containers:
      - name: p2x-temporal-ui
        image: temporalio/ui:2.20.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
        - name: TEMPORAL_ADDRESS
          value: "temporal:7233"
        - name: TEMPORAL_CORS_ORIGINS
          value: "http://localhost:3000,http://35.200.135.8:3000,https://p2x-api.bilvantis.com, https://p2x.bilvantis.com, http://p2x.bilvantis.com"
        envFrom:
          - configMapRef:
              name: p2x-config
          - secretRef:
              name: p2x-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: p2x-temporal-ui-service
  namespace: p2x
spec:
  selector:
    app: p2x-temporal-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
