apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2x-temporal-ui-deployment
  namespace: p2x
  labels:
    app: p2x-temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2x-temporal-ui
  template:
    metadata:
      labels:
        app: p2x-temporal-ui
    spec:
      containers:
      - name: p2x-temporal-ui
        image: sivareddy6244/temporal-ui:2.20.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: p2x-config
          - secretRef:
              name: genie-app-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: p2x-temporal-ui-service
  namespace: p2x
spec:
  selector:
    app: p2x-temporal-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
