apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2x-temporal-auto-setup-deployment
  namespace: p2x
  labels:
    app: p2x-temporal-auto-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2x-temporal-auto-setup
  template:
    metadata:
      labels:
        app: p2x-temporal-auto-setup
    spec:
      containers:
      - name: p2x-temporal-auto-setup
        image: sivareddy6244/temporal-auto-setup:1.22.4
        imagePullPolicy: Always
        ports:
          - containerPort: 7233
        envFrom:
          - configMapRef:
              name: p2x-config
          - secretRef:
              name: p2x-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: p2x-temporal-auto-setup-service
  namespace: p2x
spec:
  selector:
    app: p2x-temporal-auto-setup
  ports:
    - protocol: TCP
      port: 7233
      targetPort: 7233
  type: LoadBalancer
