apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2x-temporal-sql-worker-deployment
  namespace: p2x
  labels:
    app: p2x-temporal-sql-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2x-temporal-sql-worker
  template:
    metadata:
      labels:
        app: p2x-temporal-sql-worker
    spec:
      containers:
      - name: p2x-temporal-sql-worker
        image: temporal-migrateiq-workers-sql-worker:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 7233
        envFrom:
          - configMapRef:
              name: p2x-config
          - secretRef:
              name: genie-app-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: p2x-temporal-sql-worker-service
  namespace: p2x
spec:
  selector:
    app: p2x-temporal-sql-worker
  ports:
    - protocol: TCP
      port: 7233
      targetPort: 7233
  type: LoadBalancer
