apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2x-temporal-cassandra-deployment
  namespace: p2x
  labels:
    app: p2x-temporal-cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2x-temporal-cassandra
  template:
    metadata:
      labels:
        app: p2x-temporal-cassandra
    spec:
      containers:
      - name: p2x-temporal-cassandra
        image: sivareddy6244/cassandra:3.11.9
        imagePullPolicy: Always
        ports:
          - containerPort: 9042
        envFrom:
          - configMapRef:
              name: p2x-config
          - secretRef:
              name: p2x-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: p2x-temporal-cassandra-service
  namespace: p2x
spec:
  selector:
    app: p2x-temporal-cassandra
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
  type: LoadBalancer
